### ISSUE TITLE
Use tabCapture API

### ISSUE THREAD

**Issue by vantezzen** [vantezzen/skip-silence#123]
Currently, the extension uses direct media element access to analyze the volume. To improve issues with CORS, this can instead be changed to work on a per-page basis using the Chrome "tabCapture" API.

## Pros
- Makes the extension work on far more pages (especially CORS-related issues)
- May even work on pages that don't use the standard HTML5 audio elements when adding custom page drivers

## Cons
- This change is NOT compatible with Firefox
  - The feature uses the "tabCapture" API which is not implemented in Firefox and won't get in the near future (https://bugzilla.mozilla.org/show_bug.cgi?id=1391223)
  - I plan on keeping support for the current Skip Silence 4, keeping compatibility with Firefox but not having background-level capturing or making the extension compatible with both APIs based on availability
- This change is (currently) NOT compatible with Manifest v3
  - Neither tabCapture nor AudioContext is available there (https://bugs.chromium.org/p/chromium/issues/detail?id=1214847)
  - Manifest v2 is available until 01/2023 so we can hope Chrome fixes this until then
- multiple media elements on a SINGLE page cannot be analyzed independently, though I doubt anyone uses Skip silence like that

## TODO
- [x] Change Silence Skipper to work on a per-page instead of per-element level
- [x] Switch Silence Skipper to using tabCapture API
- [x] Make it work for iFrames (e.g. Google Drive #118)
- [ ] Public beta testing
