### ISSUE TITLE
Preload media

### ISSUE THREAD

**Issue by vantezzen** [vantezzen/skip-silence#77]
Currently, Skip SIlence will use the current volume to speed up and slow down. Instead, a preload element should be added that allows finding out the volume 0.1-1s in the future.

Skip Silence 2 already had such a feature but that has been removed because it was too buggy and didn't work on YouTube.

Work has already started in the v4-preload branch.

**Todo**
- [ ] Enable mute silence to work with feature
- [ ] Mute preload element
- [ ] Allow switching preload on and off without needing to reload?
- [ ] Test on example page
- [ ] Test on YouTube
